In [1]:
import os
import pandas as pd
import json
from pathlib import Path

GRADES =  list(range(1, 5))
TEXTS = ["crayfish", "trick", "zoo"]

dfs = []
for name in TEXTS:
    base = Path("./data/raw")
    df = pd.read_csv(base / "scores" / f"{name}.csv")
    audio_dir = base / "audio" / name
    df["path"] = df["ID"].astype(str).apply(lambda x: str(audio_dir / f"{x}.wav"))
    df["text"] = name
    df["test_set"] = False
    dfs.append(df)

raw_dataset = pd.concat(dfs, ignore_index=True)

raw_dataset

,ID,grade,age,gender,raven,speed,label1,path,text,test_set,comprehension,label2
0,nnd1,1,7.0,0.0,24.0,15.0,0,data\raw\audio\crayfish\nnd1.wav,crayfish,False,NaN,NaN
1,nnd10,4,9.0,1.0,32.0,75.0,0,data\raw\audio\crayfish\nnd10.wav,crayfish,False,NaN,NaN
2,nnd11,4,10.0,1.0,33.0,150.0,2,data\raw\audio\crayfish\nnd11.wav,crayfish,False,NaN,NaN
3,nnd12,4,10.0,0.0,31.0,71.0,0,data\raw\audio\crayfish\nnd12.wav,crayfish,False,NaN,NaN
4,nnd13,3,9.0,0.0,32.0,81.0,2,data\raw\audio\crayfish\nnd13.wav,crayfish,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1352,ds41,3,10.0,0.0,34.0,44.0,0,data\raw\audio\zoo\ds41.wav,zoo,False,3.0,0.0
1353,mat9,2,8.0,0.0,31.0,100.0,2,data\raw\audio\zoo\mat9.wav,zoo,False,NaN,2.0
1354,nnz45,2,9.0,0.0,33.0,46.0,1,data\raw\audio\zoo\nnz45.wav,zoo,False,6.0,1.0
1355,nnz48,2,8.0,1.0,33.0,68.0,2,data\raw\audio\zoo\nnz48.wav,zoo,False,3.0,1.0
1356,nnz75,2,8.0,0.0,33.0,51.0,2,data\raw\audio\zoo\nnz75.wav,zoo,False,6.0,2.0

In [2]:
from src.models.models import ModelInfo
from src.experiment import Experiment
from src.utils.read_datasets import read_datasets
from src.utils.encoders import AudioEncoderType

df_with_audio = read_datasets(experiment=Experiment(
    ModelInfo(None, None, None, None),
    tuple(TEXTS),
    audio_encoder_type=AudioEncoderType.whisper60s_mean.value))
df_with_audio

  1%|          | 8/1357 [00:00<00:37, 35.80it/s]

File not found for path data\raw\audio\crayfish\nnd1.wav
File not found for path data\raw\audio\crayfish\nnd10.wav
File not found for path data\raw\audio\crayfish\nnd11.wav
File not found for path data\raw\audio\crayfish\nnd12.wav
File not found for path data\raw\audio\crayfish\nnd13.wav
File not found for path data\raw\audio\crayfish\nnd14.wav
File not found for path data\raw\audio\crayfish\nnd15.wav
File not found for path data\raw\audio\crayfish\nnd16.wav

  1%|          | 12/1357 [00:00<00:36, 37.08it/s]

File not found for path data\raw\audio\crayfish\nnd17.wav
File not found for path data\raw\audio\crayfish\nnd18.wav
File not found for path data\raw\audio\crayfish\nnd19.wav
File not found for path data\raw\audio\crayfish\nnd2.wav
File not found for path data\raw\audio\crayfish\nnd20.wav
File not found for path data\raw\audio\crayfish\nnd21.wav
File not found for path data\raw\audio\crayfish\nnd22.wav
File not found for path data\raw\audio\crayfish\nnd23.wav

  2%|▏         | 21/1357 [00:00<00:34, 38.23it/s]

File not found for path data\raw\audio\crayfish\nnd24.wav
File not found for path data\raw\audio\crayfish\nnd25.wav
File not found for path data\raw\audio\crayfish\nnd26.wav
File not found for path data\raw\audio\crayfish\nnd27.wav
File not found for path data\raw\audio\crayfish\nnd28.wav
File not found for path data\raw\audio\crayfish\nnd29.wav
File not found for path data\raw\audio\crayfish\nnd3.wav
File not found for path data\raw\audio\crayfish\nnd30.wav
File not found for path data\raw\audio\crayfish\nnd31.wav

  2%|▏         | 30/1357 [00:00<00:36, 35.95it/s]

File not found for path data\raw\audio\crayfish\nnd32.wav
File not found for path data\raw\audio\crayfish\nnd33.wav
File not found for path data\raw\audio\crayfish\nnd34.wav
File not found for path data\raw\audio\crayfish\nnd35.wav
File not found for path data\raw\audio\crayfish\nnd36.wav
File not found for path data\raw\audio\crayfish\nnd37.wav
File not found for path data\raw\audio\crayfish\nnd38.wav

  3%|▎         | 39/1357 [00:01<00:34, 37.88it/s]

File not found for path data\raw\audio\crayfish\nnd39.wav
File not found for path data\raw\audio\crayfish\nnd4.wav
File not found for path data\raw\audio\crayfish\nnd40.wav
File not found for path data\raw\audio\crayfish\nnd41.wav
File not found for path data\raw\audio\crayfish\nnd42.wav
File not found for path data\raw\audio\crayfish\nnd43.wav
File not found for path data\raw\audio\crayfish\nnd44.wav
File not found for path data\raw\audio\crayfish\nnd45.wav

  4%|▎         | 48/1357 [00:01<00:33, 38.78it/s]

File not found for path data\raw\audio\crayfish\nnd46.wav
File not found for path data\raw\audio\crayfish\nnd48.wav
File not found for path data\raw\audio\crayfish\nnd49.wav
File not found for path data\raw\audio\crayfish\nnd5.wav
File not found for path data\raw\audio\crayfish\nnd50.wav
File not found for path data\raw\audio\crayfish\nnd51.wav
File not found for path data\raw\audio\crayfish\nnd52.wav
File not found for path data\raw\audio\crayfish\nnd53.wav

  4%|▍         | 56/1357 [00:01<00:34, 37.83it/s]

File not found for path data\raw\audio\crayfish\nnd54.wav
File not found for path data\raw\audio\crayfish\nnd55.wav
File not found for path data\raw\audio\crayfish\nnd56.wav
File not found for path data\raw\audio\crayfish\nnd57.wav
File not found for path data\raw\audio\crayfish\nnd58.wav
File not found for path data\raw\audio\crayfish\nnd59.wav
File not found for path data\raw\audio\crayfish\nnd6.wav
File not found for path data\raw\audio\crayfish\nnd60.wav
File not found for path data\raw\audio\crayfish\nnd61.wav

  5%|▍         | 64/1357 [00:01<00:35, 35.95it/s]

File not found for path data\raw\audio\crayfish\nnd62.wav
File not found for path data\raw\audio\crayfish\nnd63.wav
File not found for path data\raw\audio\crayfish\nnd64.wav
File not found for path data\raw\audio\crayfish\nnd65.wav
File not found for path data\raw\audio\crayfish\nnd66.wav
File not found for path data\raw\audio\crayfish\nnd67.wav
File not found for path data\raw\audio\crayfish\nnd68.wav

  5%|▌         | 68/1357 [00:01<00:35, 36.72it/s]

File not found for path data\raw\audio\crayfish\nnd69.wav
File not found for path data\raw\audio\crayfish\nnd7.wav
File not found for path data\raw\audio\crayfish\nnd70.wav
File not found for path data\raw\audio\crayfish\nnd71.wav
File not found for path data\raw\audio\crayfish\nnd72.wav
File not found for path data\raw\audio\crayfish\nnd73.wav
File not found for path data\raw\audio\crayfish\nnd74.wav

  6%|▌         | 76/1357 [00:02<00:35, 36.33it/s]

File not found for path data\raw\audio\crayfish\nnd75.wav
File not found for path data\raw\audio\crayfish\nnd76.wav
File not found for path data\raw\audio\crayfish\nnd77.wav
File not found for path data\raw\audio\crayfish\nnd78.wav
File not found for path data\raw\audio\crayfish\nnd79.wav
File not found for path data\raw\audio\crayfish\nnd8.wav
File not found for path data\raw\audio\crayfish\nnd80.wav
File not found for path data\raw\audio\crayfish\nnd81.wav

  6%|▌         | 84/1357 [00:02<00:37, 34.09it/s]

File not found for path data\raw\audio\crayfish\nnd82.wav
File not found for path data\raw\audio\crayfish\nnd83.wav
File not found for path data\raw\audio\crayfish\nnd84.wav
File not found for path data\raw\audio\crayfish\nnd85.wav
File not found for path data\raw\audio\crayfish\nnd9.wav
File not found for path data\raw\audio\crayfish\s31.wav

  8%|▊         | 112/1357 [00:02<00:12, 97.31it/s]

File not found for path data\raw\audio\crayfish\s34.wav
File not found for path data\raw\audio\crayfish\s36.wav
File not found for path data\raw\audio\crayfish\s37.wav
File not found for path data\raw\audio\crayfish\s39.wav
File not found for path data\raw\audio\crayfish\s41.wav
File not found for path data\raw\audio\crayfish\s43.wav
File not found for path data\raw\audio\crayfish\s44.wav

 10%|▉         | 135/1357 [00:02<00:15, 76.78it/s]

File not found for path data\raw\audio\crayfish\s45.wav
File not found for path data\raw\audio\crayfish\s46.wav
File not found for path data\raw\audio\crayfish\s50.wav
File not found for path data\raw\audio\crayfish\s51.wav
File not found for path data\raw\audio\crayfish\s61.wav
File not found for path data\raw\audio\crayfish\s68.wav
File not found for path data\raw\audio\crayfish\s69.wav
File not found for path data\raw\audio\crayfish\s72.wav
File not found for path data\raw\audio\crayfish\s84.wav

 11%|█         | 144/1357 [00:02<00:18, 66.77it/s]

File not found for path data\raw\audio\crayfish\s89.wav
File not found for path data\raw\audio\crayfish\s92.wav
File not found for path data\raw\audio\crayfish\s94.wav
File not found for path data\raw\audio\crayfish\s97.wav
File not found for path data\raw\audio\crayfish\s98.wav
File not found for path data\raw\audio\crayfish\s99.wav
File not found for path data\raw\audio\crayfish\s100.wav
File not found for path data\raw\audio\crayfish\s104.wav

 12%|█▏        | 161/1357 [00:03<00:17, 69.22it/s]

File not found for path data\raw\audio\crayfish\s106.wav
File not found for path data\raw\audio\crayfish\s111.wav
File not found for path data\raw\audio\crayfish\s118.wav
File not found for path data\raw\audio\crayfish\s120.wav
File not found for path data\raw\audio\crayfish\s128.wav
File not found for path data\raw\audio\crayfish\s130.wav
File not found for path data\raw\audio\crayfish\s133.wav
File not found for path data\raw\audio\crayfish\s136.wav

 13%|█▎        | 182/1357 [00:03<00:15, 74.45it/s]

File not found for path data\raw\audio\crayfish\s141.wav
File not found for path data\raw\audio\crayfish\s144.wav
File not found for path data\raw\audio\crayfish\s150.wav
File not found for path data\raw\audio\crayfish\s152.wav
File not found for path data\raw\audio\crayfish\s161.wav
File not found for path data\raw\audio\crayfish\s164.wav
File not found for path data\raw\audio\crayfish\s165.wav
File not found for path data\raw\audio\crayfish\s167.wav
File not found for path data\raw\audio\crayfish\s168.wav

 14%|█▍        | 190/1357 [00:03<00:19, 61.08it/s]

File not found for path data\raw\audio\crayfish\s169.wav
File not found for path data\raw\audio\crayfish\s170.wav
File not found for path data\raw\audio\crayfish\s171.wav
File not found for path data\raw\audio\crayfish\s172.wav
File not found for path data\raw\audio\crayfish\s173.wav
File not found for path data\raw\audio\crayfish\s176.wav
File not found for path data\raw\audio\crayfish\s177.wav
File not found for path data\raw\audio\crayfish\s178.wav

 15%|█▌        | 209/1357 [00:03<00:16, 69.60it/s]

File not found for path data\raw\audio\crayfish\s181.wav
File not found for path data\raw\audio\crayfish\s182.wav
File not found for path data\raw\audio\crayfish\m9.wav
File not found for path data\raw\audio\crayfish\m12.wav
File not found for path data\raw\audio\crayfish\m15.wav
File not found for path data\raw\audio\crayfish\m16.wav
File not found for path data\raw\audio\crayfish\m19.wav

 18%|█▊        | 241/1357 [00:04<00:09, 123.57it/s]

File not found for path data\raw\audio\crayfish\m30.wav
File not found for path data\raw\audio\crayfish\m40.wav
File not found for path data\raw\audio\crayfish\m42.wav
File not found for path data\raw\audio\crayfish\m64.wav
File not found for path data\raw\audio\crayfish\m66.wav
File not found for path data\raw\audio\crayfish\m68.wav
File not found for path data\raw\audio\crayfish\m76.wav
File not found for path data\raw\audio\crayfish\m77.wav

 19%|█▉        | 255/1357 [00:04<00:11, 96.70it/s]

File not found for path data\raw\audio\crayfish\m78.wav
File not found for path data\raw\audio\crayfish\m79.wav
File not found for path data\raw\audio\crayfish\m80.wav
File not found for path data\raw\audio\crayfish\m81.wav
File not found for path data\raw\audio\crayfish\m82.wav
File not found for path data\raw\audio\crayfish\m83.wav
File not found for path data\raw\audio\crayfish\m84.wav
File not found for path data\raw\audio\crayfish\m85.wav

 20%|█▉        | 266/1357 [00:04<00:12, 88.22it/s]

File not found for path data\raw\audio\crayfish\m86.wav
File not found for path data\raw\audio\crayfish\m89.wav
File not found for path data\raw\audio\crayfish\m91.wav
File not found for path data\raw\audio\crayfish\m96.wav
File not found for path data\raw\audio\crayfish\m101.wav
File not found for path data\raw\audio\crayfish\m102.wav
File not found for path data\raw\audio\crayfish\m103.wav

100%|██████████| 1357/1357 [00:04<00:00, 288.83it/s]

File not found for path data\raw\audio\crayfish\m107.wav
File not found for path data\raw\audio\crayfish\m110.wav
File not found for path data\raw\audio\crayfish\m111.wav
File not found for path data\raw\audio\crayfish\m112.wav
File not found for path data\raw\audio\trick\mat9.wav
Finished embedding with 169 errors and 1188 successful embeddings (total 1357).

All embeddings took 4.8244853019714355 seconds

,ID,grade,age,gender,embedding,speed,label1,orig_label1,task,test_set
84,s1,3,9.0,0.0,"[-0.030652398, -0.041544367, 3.578423, -0.0568...",102.0,2,2,crayfish,True
85,s2,1,8.0,1.0,"[-0.027453952, -0.006743636, 3.497938, -0.1157...",62.0,2,2,crayfish,True
86,s3,1,7.0,1.0,"[0.01976606, -0.07134706, 3.2134695, 0.0295509...",58.0,2,2,crayfish,True
87,s6,1,7.0,1.0,"[-0.033057317, -0.040554833, 3.5759664, -0.190...",62.0,2,2,crayfish,True
88,s9,1,7.0,0.0,"[0.07187223, -0.06201104, 3.5602334, -0.014755...",59.0,2,2,crayfish,True
...,...,...,...,...,...,...,...,...,...,...
1352,ds41,3,10.0,0.0,"[0.026192315, -0.112036355, 3.393126, 0.005873...",44.0,0,0,zoo,False
1353,mat9,2,8.0,0.0,"[0.030557588, -0.01972827, 3.3907113, -0.22281...",100.0,2,2,zoo,False
1354,nnz45,2,9.0,0.0,"[-0.06655935, -0.063964576, 3.3638148, 0.00518...",46.0,1,1,zoo,False
1355,nnz48,2,8.0,1.0,"[-0.067038774, -0.10603219, 3.3407354, -0.0449...",68.0,2,2,zoo,False
1356,nnz75,2,8.0,0.0,"[0.00865761, -0.14900646, 3.4047291, -0.080718...",51.0,2,2,zoo,False

In [3]:
print(raw_dataset["ID"].nunique())
print(df_with_audio["ID"].nunique())

710
625

In [4]:
import numpy as np


def to_native(x):
    if isinstance(x, dict):
        return {k: to_native(v) for k, v in x.items()}
    if isinstance(x, list):
        return [to_native(v) for v in x]
    if isinstance(x, np.ndarray):
        return [to_native(v) for v in x.tolist()]
    if isinstance(x, (np.integer,)):
        return int(x)
    if isinstance(x, (np.floating, float)):
        f = float(x)
        return int(f) if f.is_integer() else round(f, 2)
    if isinstance(x, (np.bool_,)):
        return bool(x)
    return x


def get_participant_stats(df, text:str, grade:int|None=None):
    stats = dict()
    
    if grade is not None:
        df = df[df["grade"] == grade]
    
    stats["grade"] = grade if grade is not None else "all"

    if "task" in df.columns:
        df = df[df["task"] == text]
    elif "text" in df.columns:
        df = df[df["text"] == text]
    else:
        raise ValueError("No 'task' or 'text' column found in the dataframe.")
    stats["text"] = text

    
    boys = df[df["gender"] == 1.0]
    girls = df[df["gender"] == 0.0]

    stats[f"total"] = {
        "total": len(df),
        "boys": boys.shape[0],
        "girls": girls.shape[0],
    }
    stats["dyslexia"] = {
        "TD_girls": ((girls["label1"] == 2)).sum(),
        "TD_boys": ((boys["label1"] == 2)).sum(),
        "R_girls": ((girls["label1"] == 1)).sum(),
        "R_boys": ((boys["label1"] == 1)).sum(),
        "D_girls": ((girls["label1"] == 0)).sum(),
        "D_boys": ((boys["label1"] == 0)).sum(),
    }
    assert sum(stats["dyslexia"].values()) == df.shape[0]
    return to_native(stats)

In [5]:
from typing import Literal

def make_row(stats):
    
    row = {
        "grade": stats['grade'],
        "text": stats['text']
    }
    counts = stats['dyslexia']
    row.update({
        **{k: v for k, v in counts.items()}
    })
    return row




def make_df_for_text(df, text):
    text_table = pd.DataFrame()


    for grade in GRADES:
        stats = get_participant_stats(df.copy(), text=text, grade=grade)
        participants_row = pd.DataFrame([make_row(stats)])
        participants_row["grade_count"] = participants_row[["TD_boys", "TD_girls", "R_boys", "R_girls", "D_boys", "D_girls"]].sum(axis=1)
        text_table = pd.concat([text_table, participants_row], ignore_index=True)
    
    total_row = text_table.sum().to_frame().T
    total_row["grade"] = "total"
    total_row["text"] = text

    text_table = pd.concat([total_row, text_table], ignore_index=True)

    return text_table


def format_df(df):
    def format_group_value(row, group:Literal["TD", "R", "D"]):
        boys = row[f"{group}_boys"]
        girls = row[f"{group}_girls"]
        formatted_group_value =  f"{boys+girls}\n({girls} girls, {boys} boys)"
        return formatted_group_value


    result = pd.DataFrame(columns=["Group", "TD", "R", "D"])
    for _, row in df.iterrows():
        group_row = {
            "Group": f"Grade {row['grade']}\nN={row['grade_count']}",
            **{
                group: format_group_value(row, group) for group in ["TD", "R", "D"]
            },
        }
        result = pd.concat([result, pd.DataFrame([group_row])], ignore_index=True)
    return result

In [6]:


def make_exploratory_table(df):
    text_dfs = {
        text: format_df(make_df_for_text(df, text)) for text in TEXTS
    }

    final_df = pd.DataFrame()
    for grade in GRADES:
        temp_df = pd.DataFrame()
        for k, v in text_dfs.items():
            temp_df = pd.concat([temp_df, v[v["Group"].str.contains(f"Grade {grade}")].assign(Text=k)], ignore_index=True)
        final_df = pd.concat([final_df, temp_df], ignore_index=True)
    return final_df

In [7]:
raw_df = make_exploratory_table(raw_dataset)
raw_df

,Group,TD,R,D,Text
0,Grade 1\nN=96,"65\n(28 girls, 37 boys)","11\n(7 girls, 4 boys)","20\n(5 girls, 15 boys)",crayfish
1,Grade 1\nN=84,"74\n(39 girls, 35 boys)","10\n(3 girls, 7 boys)","0\n(0 girls, 0 boys)",trick
2,Grade 1\nN=88,"70\n(40 girls, 30 boys)","11\n(5 girls, 6 boys)","7\n(3 girls, 4 boys)",zoo
3,Grade 2\nN=99,"71\n(46 girls, 25 boys)","11\n(3 girls, 8 boys)","17\n(6 girls, 11 boys)",crayfish
4,Grade 2\nN=122,"98\n(63 girls, 35 boys)","13\n(5 girls, 8 boys)","11\n(9 girls, 2 boys)",trick
5,Grade 2\nN=145,"114\n(67 girls, 47 boys)","18\n(8 girls, 10 boys)","13\n(6 girls, 7 boys)",zoo
6,Grade 3\nN=116,"87\n(47 girls, 40 boys)","6\n(3 girls, 3 boys)","23\n(13 girls, 10 boys)",crayfish
7,Grade 3\nN=117,"96\n(51 girls, 45 boys)","11\n(5 girls, 6 boys)","10\n(7 girls, 3 boys)",trick
8,Grade 3\nN=134,"97\n(49 girls, 48 boys)","21\n(6 girls, 15 boys)","16\n(9 girls, 7 boys)",zoo
9,Grade 4\nN=108,"77\n(39 girls, 38 boys)","5\n(2 girls, 3 boys)","26\n(10 girls, 16 boys)",crayfish
10,Grade 4\nN=117,"97\n(51 girls, 46 boys)","10\n(6 girls, 4 boys)","10\n(3 girls, 7 boys)",trick
11,Grade 4\nN=131,"106\n(60 girls, 46 boys)","13\n(4 girls, 9 boys)","12\n(4 girls, 8 boys)",zoo

In [8]:
audio_df = make_exploratory_table(df_with_audio)
audio_df

,Group,TD,R,D,Text
0,Grade 1\nN=53,"38\n(14 girls, 24 boys)","5\n(3 girls, 2 boys)","10\n(2 girls, 8 boys)",crayfish
1,Grade 1\nN=84,"74\n(39 girls, 35 boys)","10\n(3 girls, 7 boys)","0\n(0 girls, 0 boys)",trick
2,Grade 1\nN=88,"70\n(40 girls, 30 boys)","11\n(5 girls, 6 boys)","7\n(3 girls, 4 boys)",zoo
3,Grade 2\nN=56,"38\n(24 girls, 14 boys)","4\n(2 girls, 2 boys)","14\n(4 girls, 10 boys)",crayfish
4,Grade 2\nN=121,"97\n(62 girls, 35 boys)","13\n(5 girls, 8 boys)","11\n(9 girls, 2 boys)",trick
5,Grade 2\nN=145,"114\n(67 girls, 47 boys)","18\n(8 girls, 10 boys)","13\n(6 girls, 7 boys)",zoo
6,Grade 3\nN=79,"59\n(32 girls, 27 boys)","4\n(2 girls, 2 boys)","16\n(7 girls, 9 boys)",crayfish
7,Grade 3\nN=117,"96\n(51 girls, 45 boys)","11\n(5 girls, 6 boys)","10\n(7 girls, 3 boys)",trick
8,Grade 3\nN=134,"97\n(49 girls, 48 boys)","21\n(6 girls, 15 boys)","16\n(9 girls, 7 boys)",zoo
9,Grade 4\nN=63,"46\n(24 girls, 22 boys)","3\n(0 girls, 3 boys)","14\n(6 girls, 8 boys)",crayfish
10,Grade 4\nN=117,"97\n(51 girls, 46 boys)","10\n(6 girls, 4 boys)","10\n(3 girls, 7 boys)",trick
11,Grade 4\nN=131,"106\n(60 girls, 46 boys)","13\n(4 girls, 9 boys)","12\n(4 girls, 8 boys)",zoo